### ISSUE TITLE
Instead of setting the network values, read them from the beacon nodes

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/forky#71]
Currently forky reads the spec values from a config file.

This is error prone, if you want to use forky on a non standard setup.

It would make sense to read the spec values from the beacon node that it is connected to.

```yaml
spec:
   seconds_per_slot: 12
   slots_per_epoch: 32
   genesis_time: <genesis-time>
```

These values could be queried from:

`/eth/v1/config/spec | jq .data.SECONDS_PER_SLOT`
`/eth/v1/config/spec | jq .data.SLOTS_PER_EPOCH`
`/eth/v1/config/spec | jq .data.MIN_GENESIS_TIME + GENESIS_DELAY`
